import os
import sys
import subprocess
import numpy as np
from ase.optimize import BFGS, FIRE
from ase.optimize.sciopt import SciPyFminCG
from ase.calculators.emt import EMT
from ase.io import write, read
from ase.data import atomic_numbers, atomic_masses

class LammpsMLIAPEngine:
    """
    Interface for calling an external LAMMPS binary with ML-IAP (SevenNet/MACE) 
    and custom D3 dispersion overlay.
    """
    def __init__(self, binary_path, model_path, potential_type='sevennet', d3_params=None, parallel=False, nmpl=1):
        self.binary_path = binary_path
        self.model_path = model_path
        self.potential_type = potential_type.lower()
        self.d3_params = d3_params # Dict: {'s6': 9000, 's8': 1600, 'damping': 'damp_bj', 'functional': 'pbe'}
        self.parallel = parallel
        self.nmpl = nmpl
        
    def _create_input_script(self, atoms, input_file, data_file, log_file):
        """Generates LAMMPS input script for ML-IAP + D3 overlay."""
        # Species must be sorted by atomic number for consistent LAMMPS typing if required,
        # but primarily to match the user's provided logic for SevenNet.
        species = sorted(list(set(atoms.get_chemical_symbols())), key=lambda x: atomic_numbers[x])
        species_str = " ".join(species)
        
        # Determine atom_style (full is safer for molecular systems)
        atom_style = "full" 
        write(data_file, atoms, format='lammps-data', atom_style=atom_style)
        
        lines = [
            "# Generated by AutoFlow-SRXN LammpsMLIAPEngine",
            "units metal",
            "boundary p p p",
            f"atom_style {atom_style}",
            "newton on",
            f"read_data {data_file}",
            ""
        ]
        
        # Add mass definitions
        for idx, elem in enumerate(species):
            mass = atomic_masses[atomic_numbers[elem]]
            lines.append(f"mass {idx+1} {mass:.4f}")
        lines.append("")

        if self.potential_type == 'sevennet':
            if not self.parallel:
                lines.append(f"pair_style e3gnn")
                lines.append(f"pair_coeff * * {self.model_path} {species_str}")
            else:
                lines.append(f"pair_style e3gnn/parallel")
                lines.append(f"pair_coeff * * {self.nmpl} {self.model_path} {species_str}")
        elif self.potential_type == 'mace':
            # Keep existing logic or update if MACE also needs special handling.
            # Assuming mliap unified was previously used for MACE-like interfaces
            lines.append(f"pair_style mliap unified {self.model_path} 0")
            lines.append(f"pair_coeff * * MACE {species_str}")
        else:
            # Fallback
            lines.append(f"pair_style mliap unified {self.model_path} 0")
            lines.append(f"pair_coeff * * {self.potential_type} {species_str}")

        if self.d3_params:
            # Note: hybrid/overlay logic for e3gnn would need careful handling.
            # Currently assuming the user's snippet is the priority for the base style.
            # If d3 is needed as overlay:
            d3 = self.d3_params
            lines.insert(-2, f"pair_style hybrid/overlay {lines.pop(-2)}") # wrap existing style
            lines.append(f"pair_style d3 {d3['s6']} {d3['s8']} {d3['damping']} {d3['functional']}")
            lines.append(f"pair_coeff * * d3 {species_str}")
            
        lines.extend([
            "",
            "neighbor 1.0 bin",
            "neigh_modify delay 0 every 1 check yes",
            "thermo 1",
            "thermo_style custom step potential",
            "dump 1 all custom 1 dump.forces id fx fy fz",
            "dump_modify 1 sort id",
            "run 0"
        ])
        
        with open(input_file, 'w') as f:
            f.write("\n".join(lines))

    def calculate(self, atoms):
        """Executes LAMMPS and returns energy and forces."""
        wd = "lammps_run"
        if not os.path.exists(wd): os.makedirs(wd)
        
        input_file = os.path.join(wd, "in.lammps")
        data_file = os.path.join(wd, "data.lammps")
        log_file = os.path.join(wd, "log.lammps")
        dump_file = os.path.join(wd, "dump.forces")
        
        self._create_input_script(atoms, input_file, data_file, log_file)
        
        # Execute LAMMPS
        cmd = [self.binary_path, "-in", "in.lammps", "-log", "log.lammps"]
        subprocess.run(cmd, cwd=wd, check=True, capture_output=True, text=True)
            
        # Parse log for energy
        energy = 0.0
        with open(log_file, 'r') as f:
            lines = f.readlines()
            for i, line in enumerate(lines):
                if "Step Pot" in line:
                    data_line = lines[i+1].split()
                    energy = float(data_line[1])
                    break
        
        # Parse dump for forces
        forces = np.zeros((len(atoms), 3))
        with open(dump_file, 'r') as f:
            lines = f.readlines()
            parsing_atoms = False
            for line in lines:
                if "ITEM: ATOMS" in line:
                    parsing_atoms = True
                    continue
                if parsing_atoms:
                    parts = line.split()
                    if len(parts) == 4:
                        idx = int(parts[0]) - 1 # 1-indexed to 0-indexed
                        forces[idx] = [float(parts[1]), float(parts[2]), float(parts[3])]
        
        return energy, forces

    def relax(self, atoms, fmax=0.05, steps=200):
        """Performs structural relaxation using LAMMPS minimize."""
        wd = "lammps_relax"
        if not os.path.exists(wd): os.makedirs(wd)
        
        input_file = os.path.join(wd, "in.lammps")
        data_file = os.path.join(wd, "data.lammps")
        
        species = list(set(atoms.get_chemical_symbols()))
        species_str = " ".join(species)
        atom_style = "full"
        write(data_file, atoms, format='lammps-data', atom_style=atom_style)
        
        lines = [
            "units metal",
            "boundary p p p",
            f"atom_style {atom_style}",
            "newton on",
            f"read_data {data_file}",
            ""
        ]
        
        if self.d3_params:
            d3 = self.d3_params
            lines.append(f"pair_style hybrid/overlay mliap unified {self.model_path} 0 d3 {d3['s6']} {d3['s8']} {d3['damping']} {d3['functional']}")
            lines.append(f"pair_coeff * * mliap SevenNet {species_str}")
            lines.append(f"pair_coeff * * d3 {species_str}")
        else:
            lines.append(f"pair_style mliap unified {self.model_path} 0")
            lines.append(f"pair_coeff * * SevenNet {species_str}")
            
        lines.extend([
            "",
            "neighbor 1.0 bin",
            "neigh_modify delay 0 every 1 check yes",
            f"minimize 0.0 {fmax} {steps} {steps*10}",
            f"write_data {data_file}.relaxed"
        ])
        
        with open(input_file, 'w') as f:
            f.write("\n".join(lines))
            
        cmd = [self.binary_path, "-in", "in.lammps", "-log", "log.lammps"]
        subprocess.run(cmd, cwd=wd, check=True, capture_output=True)
        
        # Load relaxed geometry
        relaxed_atoms = read(os.path.join(wd, f"{data_file}.relaxed"), format='lammps-data', style=atom_style)
        # Update original atoms positions
        atoms.positions = relaxed_atoms.positions
        return 0.0 # Energy parsing omitted for brevity

class SimulationEngine:
    """
    High-level engine for structural relaxation and energy extraction.
    """
    def __init__(self, model_type='mace', device='cpu', config=None):
        self.model_type = model_type.lower()
        self.device = device
        self.config = config or {}
        self._calculator = None
        self._lammps_engine = None

        if self.model_type in ['sevennet_mliap', 'sevennet']:
            self._lammps_engine = LammpsMLIAPEngine(
                binary_path=self.config.get('lammps', {}).get('binary_path'),
                model_path=self.config.get('lammps', {}).get('model_path'),
                potential_type='sevennet',
                d3_params=self.config.get('lammps', {}).get('d3')
            )

    def get_calculator(self):
        if self._calculator is not None:
            return self._calculator

        if self.model_type == 'emt':
            self._calculator = EMT()
        elif 'mace' in self.model_type:
            try:
                from mace.calculators import mace_mp
                self._calculator = mace_mp(model="medium", device=self.device, default_dtype="float32")
                print(f"  [SimulationEngine] Loaded MACE-MP calculator.")
            except ImportError:
                print("  [Warning] MACE not found. Falling back to EMT.")
                self._calculator = EMT()
        else:
            self._calculator = EMT()
            
        return self._calculator

    def relax(self, atoms, fmax=0.05, steps=200, optimizer='BFGS', verbose=True):
        if self._lammps_engine:
            return self._lammps_engine.relax(atoms, fmax=fmax, steps=steps)
        
        calc = self.get_calculator()
        atoms.calc = calc
        
        if optimizer.upper() == 'CG_FIRE':
            # Stage 1: Conjugate Gradient for initial descent (looser threshold)
            # SciPyFminCG follows slightly different signature but works with run(fmax)
            fmax_cg = max(fmax * 10, 0.05)
            if verbose: print(f"  [Relax] Stage 1: SciPyFminCG (fmax={fmax_cg})")
            dyn_cg = SciPyFminCG(atoms, logfile=sys.stdout if verbose else None)
            dyn_cg.run(fmax=fmax_cg, steps=steps // 2)
            
            # Stage 2: FIRE for tight convergence
            if verbose: print(f"  [Relax] Stage 2: FIRE (fmax={fmax})")
            dyn_fire = FIRE(atoms, logfile=sys.stdout if verbose else None)
            dyn_fire.run(fmax=fmax, steps=steps)
        else:
            opt_class = BFGS if optimizer.upper() == 'BFGS' else FIRE
            dyn = opt_class(atoms, logfile=sys.stdout if verbose else None)
            dyn.run(fmax=fmax, steps=steps)
            
        return atoms.get_potential_energy()

    def get_forces(self, atoms):
        if self._lammps_engine:
            _, forces = self._lammps_engine.calculate(atoms)
            return forces
        calc = self.get_calculator()
        atoms.calc = calc
        return atoms.get_forces()
